import Nav from '@/components/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DPS 360',
  description: 'Generated by create next app',
}

const navItems = [
  {
    text: "About Us",
    href: "/about"
  },
  {
    text: "Coaching",
    href: "/coaching"
  },
  {
    text: "Contact",
    href: "/contact"
  },
  {
    text: "Programs",
    href: "/events"
  },
  
]

export default function RootLayout({children,}: {children: React.ReactNode}) {


  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen relative`}>
        <Nav/>
        <main className="pb-16">
          {children}
        </main>
        <footer className='absolute bottom-0 w-full bg-themeGreen text-white px-4 py-4'>
          Differentials Planet Soccer 360 | 508 Felicia Street Durham NC 27704 | info@dpsoccer360.com | (336) 417-7759
        </footer>
      </body>
    </html>
  )
}
